# Server configuration (Port 8081 used to avoid conflicts with system AgentService on 8080)
server.port=8081

# Application details
spring.application.name=cargo-ship-route-tracker

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Logging
logging.level.com.cargotracker=INFO
logging.level.eu.europa.ec.eurostat=WARN
